### ISSUE TITLE
pod install fails when cocoapods-keys is installed

### ISSUE THREAD

**Issue by davbeck** [orta/cocoapods-keys#34]
### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin12.0]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 2.2.1
Ruby lib dir : /Users/davbeck/.rvm/rubies/ruby-2.1.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b1408f2799570977598f90cffaceb4025868408d
```

### Plugins

```
cocoapods-keys    : 0.9.5
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

target 'TheCityAdminAPI', :exclusive => true do
  pod "TheCityAdminAPI", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TheCityAdminAPI", :path => "../"

  
end
```

### Error

```
NoMethodError - undefined method `add_file_references' for nil:NilClass
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-keys-0.9.5/lib/installer.rb:40:in `block in install!'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-keys-0.9.5/lib/installer.rb:15:in `install!'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-keys-0.9.5/lib/plugin.rb:6:in `block in <module:CocoaPodsKeys>'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/hooks_manager.rb:56:in `call'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/hooks_manager.rb:56:in `block in run'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/hooks_manager.rb:55:in `each'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/hooks_manager.rb:55:in `run'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:326:in `run_plugins_post_install_hooks'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:318:in `perform_post_install_actions'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:94:in `install!'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/Users/davbeck/.rvm/gems/ruby-2.1.0/bin/pod:23:in `load'
/Users/davbeck/.rvm/gems/ruby-2.1.0/bin/pod:23:in `<main>'
/Users/davbeck/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/Users/davbeck/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Gurpartap** [comment]
Have you tried it with `cocoapods 0.36.0.beta.2` yet?

**Comment by ashfurrow** [comment]
Can you look in your `Gemfile.lock` file and tell us what version of `cocoapods-keys` you have?

**Comment by orta** [comment]
( It's definitely not master, as `installer.rb` doesn't exist anymore. )
@davbeck until CocoaPods 0.36 is out properly, we've been working on framework support on master but not releasing it as a gem release. It'd be good if you used a Gemfile and set it to use the [master](https://github.com/artsy/eidolon/blob/master/Gemfile#L5) and retry..

**Comment by segiddins** [comment]
It's CocoaPods-key 0.9.5 as listed in the error report.

**Comment by orta** [comment]
ah, that got pushed to rubygems. Maybe it makes sense to push 1.0.0 too

**Comment by orta** [comment]
```
   cocoapods-keys   master ✔  gem push pkg/cocoapods-keys-1.0.0.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: cocoapods-keys (1.0.0)
```

I've just his second pushed 1.0.0, which should fix this, can you try?

**Comment by davbeck** [comment]
Does 1.0.0 require CocoaPods 0.36.0?

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin12.0]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 2.2.1
Ruby lib dir : /Users/davbeck/.rvm/rubies/ruby-2.1.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1081a0edd018f84295f2ee5d9f79c81cca0fd767
```

### Plugins

```
cocoapods-keys    : 1.0.0
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

target 'TheCityAdminAPI', :exclusive => true do
  pod "TheCityAdminAPI", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TheCityAdminAPI", :path => "../"

  
end
```

### Error

```
NoMethodError - undefined method `plugins' for #<Pod::Podfile:0x00000103094ad0>
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-keys-1.0.0/lib/plugin.rb:29:in `user_options'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-keys-1.0.0/lib/plugin.rb:17:in `setup'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-keys-1.0.0/lib/plugin.rb:39:in `install!'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/davbeck/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/Users/davbeck/.rvm/gems/ruby-2.1.0/bin/pod:23:in `load'
/Users/davbeck/.rvm/gems/ruby-2.1.0/bin/pod:23:in `<main>'
/Users/davbeck/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/Users/davbeck/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by orta** [comment]
Afraid so, to support framework based pods ( as well as static libs ) we had to migrate to only working with 0.36.

**Comment by ricardopereira** [comment]
I'm with the same error.

### Command

```
/usr/bin/pod install
```

### Stack

```
   CocoaPods : 0.36.0.beta.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.1.1 (6A2006)
         Git : git version 2.2.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ab7d13f3bc43e8638ac2167b5c3bdff76915c180
```

### Plugins

```
cocoapods-deintegrate : 0.2.0
cocoapods-keys        : 1.0.0
cocoapods-plugins     : 0.4.0
cocoapods-trunk       : 0.1.4
cocoapods-try         : 0.4.3
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Chapter3' do

pod 'Spring', '~> 1.0.1'

end

target 'Chapter3Tests' do

end
```

### Error

```
NoMethodError - undefined method `[]' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.0.0/lib/preinstaller.rb:13:in `setup'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.0.0/lib/plugin.rb:17:in `setup'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.0.0/lib/plugin.rb:39:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by ashfurrow** [comment]
Looks like there are no keys registered in the Podfile. Instructions are [here](https://github.com/orta/cocoapods-keys#usage-via-cocoapods-036), which have changed from earlier versions.

**Comment by ricardopereira** [comment]
With **cocoapods-keys** it is a requirement to have a record with keys in the Podfile?

**Comment by ashfurrow** [comment]
Yes exactly.

**Comment by Gurpartap** [comment]
Unless you got it right I think it should be cleared that you don't need to put your actual keys in the Podfile. Just the definitions of what keys you want cocoapods-keys to manage for you (it'll prompt for the actual keys when you pod install). So take those "MixpanelProductionAPIClientKey", etc. in the usage information literally.

**Comment by orta** [comment]
#40 fixes this

**Comment by esttorhe** [comment]
Don't know if this is related but it does seem like it (to me at least)

---

### Command

```
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/pod install
```

### Report

* What did you do?
  Ran `pod install`

* What did you expect to happen?
  "Installation" of all `pods` and the initialization of the `cocoapods-keys`

* What happened instead?
  `pod install` crashed after installing all the `pods`


### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D87h)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 2.2.1
Ruby lib dir : /Users/creegan/.rvm/rubies/ruby-2.1.2/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 0ac451b4b5ad3b6251c77663014b51a0048dde7e
               master - git://github.com/CocoaPods/Specs.git @ 6f4cd6159d34d7a04e9d3caa16c9ac02d37788bc
               master-1 - https://github.com/CocoaPods/Specs.git @ b2e4f75408a042a029811a9e61dd512018f4a269
```

### Plugins

```
cocoapods-browser : 0.1.5
cocoapods-keys    : 1.0.1
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '7.1'

source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

xcodeproj 'ProjectName'

pod 'CocoaLumberjack', '~> 1.9.2'
pod 'KZAsserts', '~> 1.0'
pod 'ReactiveCocoa'
pod 'ReactiveViewModel'
pod 'MBProgressHUD'
pod 'libextobjc'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'TSMessages', '~> 0.9.11'
pod 'NSString-Email', '~> 0.0.3'
pod 'TTTAttributedLabel'
pod 'ETFormatter', '~> 1.0'
pod 'ETAssert', '~> 1.0.1'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'MustOverride', '~> 1.1'

target 'ProjectNameTests', :exclusive => true do
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta+Snapshots', '~> 1.2.1'
end

plugin 'cocoapods-keys', {
	:project => "ProjectName",
	:keys => [
	"OAuthClientSecret",
	"OAuthClientId"
	]
}

class ::Pod::Generator::Acknowledgements
  def header_text
    "ProjectName uses 'CocoaPods' to link with the following 3rd Party Libraries:"
  end
end
```

### Error

```
NoMethodError - undefined method `*' for nil:NilClass
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/key_master.rb:22:in `generate_data'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/key_master.rb:13:in `initialize'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:8:in `new'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:8:in `podspec_for_current_project'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:66:in `from_string'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-core-0.36.0/lib/cocoapods-core/specification.rb:536:in `from_file'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:142:in `store_podspec'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `block in pre_download'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/abstract_external_source.rb:99:in `pre_download'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:189:in `analyze'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:40:in `install!'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Users/creegan/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/creegan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

---

I do have the keys specified on my `Podfile` like this:

```ruby
plugin 'cocoapods-keys', {
	:project => "ProjectName",
	:keys => [
	"OAuthClientSecret",
	"OAuthClientId"
	]
}
```
