### ISSUE TITLE
Can't update keys on 1.0.0 without Podfile support

### ISSUE THREAD

**Issue by lazerwalker** [orta/cocoapods-keys#37]
I had a project using cocoapods-keys pre-1.0.0, so I wasn't using the new CocoaPods 0.36 plugin API.

After upgrading to 1.0.0, updating my keys when running a `pod install` consistently fails.

```rb
NoMethodError - undefined method `[]' for nil:NilClass
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-keys-1.0.0/lib/preinstaller.rb:13:in `setup'
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-keys-1.0.0/lib/plugin.rb:17:in `setup'
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-keys-1.0.0/lib/plugin.rb:39:in `install!'
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247@global/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command.rb:45:in `run'
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.36.0.beta.2/bin/pod:44:in `<top (required)>'
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `load'
/Users/michaelwalker/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `<main>'
```

It looks like `plugin.rb` assumes that there is a cocoapods-keys plugin section of the Podfile, and isn't doing any error handling in the case that it doesn't exist.

It might be perfectly reasonable to require that people use the Podfile syntax going forward, but still worth calling out.

**Comment by ashfurrow** [comment]
Hmm. Yeah good point. Sounds like we can check for that and provide a better error message to the user.

**Comment by orta** [comment]
Given that CP 0.36 is around the corner, saying podfile plugin only could be a good option.

**Comment by ashfurrow** [comment]
:+1:

**Comment by lazerwalker** [comment]
:+1:. I was more than happy to switch to the plugin, and saying plugin only makes perfect sense to me. 

But a warning of "hey, your old setup might break" does seem reasonable.

**Comment by orta** [comment]
#39 fixes this.
